In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv("data/merged_soil_intersects.csv")

In [3]:
df.isna().sum()

point_id                    0
ph_2015                     0
ec_2015                     0
oc_2015                     0
caco3_2015                  0
p_2015                      0
n_2015                      0
k_2015                      0
elevation_2015              0
lc1_2015                    0
lu1_2015                    0
ph_2018                     0
ec_2018                     5
oc_2018                     0
caco3_2018               5841
p_2018                      6
n_2018                      0
k_2018                      0
elevation_2018              0
lc1_2018                    0
lu1_2018                    0
bd_0_10                  8196
bd_10_20                 8421
survey_erosion_signs    12827
ph_2009                     0
oc_2009                     0
caco3_2009                  0
p_2009                      0
n_2009                      0
k_2009                      0
elevation_2009              0
lc1_2009                    0
lu1_2009                    0
dtype: int64

In [4]:
df["caco3_2018"].dropna()

16        38
19         5
31        58
37        11
43       117
        ...
13270      6
13276      1
13277    117
13279     11
13280      5
Name: caco3_2018, Length: 7442, dtype: object

In [5]:
array=df["caco3_2018"].unique()

In [6]:
no_df=df.replace('<  LOD',np.nan)

In [7]:
def convert_to_number(string):

   
    try:
        return float(string)
    except:
        print(string)
        return string

In [8]:
no_df["caco3_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

94.0203820799139

In [9]:
df["caco3_2018"][df["caco3_2018"].isna()]=no_df["caco3_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

C:\Users\vibu\AppData\Local\Temp\ipykernel_30172\293234431.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["caco3_2018"][df["caco3_2018"].isna()]=no_df["caco3_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

In [10]:
df["ec_2018"][df["ec_2018"].isna()]=no_df["ec_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

C:\Users\vibu\AppData\Local\Temp\ipykernel_30172\1927307765.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["ec_2018"][df["ec_2018"].isna()]=no_df["ec_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

In [11]:
df["p_2018"].unique

<bound method Series.unique of 0           15
1           13
2         29.9
3         51.3
4         17.8
         ...
13278     19.7
13279       24
13280       10
13281    < LOD
13282     13.9
Name: p_2018, Length: 13283, dtype: object>

In [12]:
no_df=df.replace('< LOD',np.nan)

In [13]:
df["p_2018"][df["p_2018"].isna()]=no_df["p_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

C:\Users\vibu\AppData\Local\Temp\ipykernel_30172\1019213591.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["p_2018"][df["p_2018"].isna()]=no_df["p_2018"].dropna().apply(lambda x: convert_to_number(x)).mean()

In [14]:
df["bd_0_10"][df["bd_0_10"].isna()]=no_df["bd_0_10"].dropna().apply(lambda x: convert_to_number(x)).mean()

C:\Users\vibu\AppData\Local\Temp\ipykernel_30172\2533959869.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bd_0_10"][df["bd_0_10"].isna()]=no_df["bd_0_10"].dropna().apply(lambda x: convert_to_number(x)).mean()

In [15]:
df["bd_10_20"][df["bd_10_20"].isna()]=no_df["bd_10_20"].dropna().apply(lambda x: convert_to_number(x)).mean()

C:\Users\vibu\AppData\Local\Temp\ipykernel_30172\3825662169.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["bd_10_20"][df["bd_10_20"].isna()]=no_df["bd_10_20"].dropna().apply(lambda x: convert_to_number(x)).mean()

In [16]:
df.isna().sum()

point_id                    0
ph_2015                     0
ec_2015                     0
oc_2015                     0
caco3_2015                  0
p_2015                      0
n_2015                      0
k_2015                      0
elevation_2015              0
lc1_2015                    0
lu1_2015                    0
ph_2018                     0
ec_2018                     0
oc_2018                     0
caco3_2018                  0
p_2018                      0
n_2018                      0
k_2018                      0
elevation_2018              0
lc1_2018                    0
lu1_2018                    0
bd_0_10                     0
bd_10_20                    0
survey_erosion_signs    12827
ph_2009                     0
oc_2009                     0
caco3_2009                  0
p_2009                      0
n_2009                      0
k_2009                      0
elevation_2009              0
lc1_2009                    0
lu1_2009                    0
dtype: int64

In [17]:
num_col=[col for col in df.columns if df[col].dtypes!="O" ]
cat_col=[col for col in df.columns if df[col].dtypes=="O" ]

In [18]:
df[cat_col]

,lc1_2015,lu1_2015,oc_2018,caco3_2018,p_2018,n_2018,k_2018,lc1_2018,lu1_2018,lc1_2009,lu1_2009
0,C21,U120,66.1,94.020382,15,4.6,99.8,C21,U120,C20,U120
1,C22,U120,64,94.020382,13,2.6,44,C22,U120,C20,U361
2,D20,U420,102.1,94.020382,29.9,8.1,238.7,D20,U111,D20,U111
3,E20,U120,340.5,94.020382,51.3,28,128.5,E20,U120,E10,U120
4,D20,U111,147.2,94.020382,17.8,9.3,240.2,D20,U111,E20,U111
...,...,...,...,...,...,...,...,...,...,...,...
13278,E20,U111,36.2,94.020382,19.7,4.6,141.4,E20,U111,E20,U111
13279,E20,U111,62,11,24,7.1,146.1,E20,U111,E20,U111
13280,E20,U111,52.3,5,10,5.6,96.8,E20,U111,E20,U111
13281,E20,U111,27.1,94.020382,< LOD,3.4,45.7,E20,U111,E20,U111
13282,C10,U120,23.1,94.020382,13.9,2.1,185.8,C10,U120,C10,U120

In [19]:
"C120"[-3:]

'120'

In [20]:
df["lc1_2018"].unique()

array(['C21', 'C22', 'D20', 'E20', 'C10', 'C33', 'B11', 'B22', 'B41',
       'B15', 'E30', 'B23', 'B55', 'B16', 'F40', 'B32', 'B13', 'B21',
       'A22', 'B43', 'B71', 'A30', 'E10', 'B72', 'C32', 'B31', 'B52',
       'B12', 'B53', 'D10', 'C31', 'B73', 'C23', 'H12', 'F30', 'H11',
       'B14', 'B54', 'F20', 'B35', 'B51', 'Bx1', 'B75', 'B82', 'B74',
       'B19', 'B81', 'B84', 'F10', 'B44', 'B18', 'B45', 'B37', 'B83',
       'B42', 'B33', 'B17', 'B77', 'H22', 'B76', 'B34', 'G21', 'B36',
       'A21'], dtype=object)

In [21]:
for i in ["lc1_2015","lc1_2009"]:
    print(i)
    df[i]=df[i].apply(lambda x:(ord(x[:1])-64)*100+int(x[1:3]) )

lc1_2015
lc1_2009

In [22]:
df["lc1_2015"]

0        321
1        322
2        420
3        520
4        420
        ...
13278    520
13279    520
13280    520
13281    520
13282    310
Name: lc1_2015, Length: 13283, dtype: int64

In [23]:
def replace(x):
    try:
        return(ord(x[:1])-64)*100+int(x[1:3])
    except:
        return(ord(x[:1])-64)*100+int(x[2:3])

In [24]:
def replace_lu(x):
    try:
        return(ord(x[:1])-64)*1000+int(x[1:3])
    except:
        return(ord(x[:1])-64)*1000+int(x[2:3])

In [25]:
df["lc1_2018"]=df["lc1_2018"].apply(lambda x: replace(x))

In [26]:
for i in ["lu1_2015","lu1_2009","lu1_2018"]:
    print(i)
    df[i]=df[i].apply(lambda x: replace_lu(x))

lu1_2015
lu1_2009
lu1_2018

In [27]:
df

,point_id,ph_2015,ec_2015,oc_2015,caco3_2015,p_2015,n_2015,k_2015,elevation_2015,lc1_2015,...,survey_erosion_signs,ph_2009,oc_2009,caco3_2009,p_2009,n_2009,k_2009,elevation_2009,lc1_2009,lu1_2009
0,33883766,3.8,41.50,103.1,0.0,34.7,7.7,69.6,375.0,321,...,NaN,3.92,285.3,0.0,1092.76,14.1,209.3,340.0,320,21012
1,35363916,3.2,4.21,17.9,0.0,20.8,0.8,7.9,68.0,322,...,NaN,3.01,205.7,0.0,278.45,6.1,246.0,8.0,320,21036
2,33823392,3.9,43.00,96.3,0.0,31.6,7.8,93.5,243.0,420,...,NaN,4.37,274.7,0.0,570.20,17.3,210.0,179.0,420,21011
3,33983652,4.0,58.80,368.3,0.0,41.3,24.3,94.1,276.0,520,...,NaN,3.58,405.0,1.0,1264.19,22.8,98.1,222.0,510,21012
4,35383866,4.0,146.90,128.8,0.0,40.0,9.8,195.8,406.0,420,...,NaN,4.60,288.7,0.0,780.83,14.8,530.6,346.0,520,21011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13278,45542694,5.0,10.00,16.8,0.0,3.5,2.0,35.7,885.0,520,...,NaN,5.75,36.6,2.0,1017.05,3.7,89.5,879.0,520,21011
13279,45402772,6.9,81.00,49.9,8.0,49.3,5.6,200.1,477.0,520,...,NaN,6.67,26.3,6.0,826.83,1.4,250.0,430.0,520,21011
13280,45882618,6.8,65.10,53.9,3.0,16.6,5.9,90.0,630.0,520,...,NaN,6.99,35.6,13.0,1202.65,3.5,58.6,619.0,520,21011
13281,45342706,6.0,30.70,24.2,0.0,4.6,3.2,32.7,719.0,520,...,NaN,5.66,24.5,1.0,940.35,2.9,41.1,710.0,520,21011
13282,47742660,4.2,7.30,26.0,0.0,9.6,2.2,162.0,344.0,310,...,NaN,4.18,25.5,0.0,911.54,1.9,146.5,342.0,310,21012

In [28]:
df["p_2018"].unique

<bound method Series.unique of 0           15
1           13
2         29.9
3         51.3
4         17.8
         ...
13278     19.7
13279       24
13280       10
13281    < LOD
13282     13.9
Name: p_2018, Length: 13283, dtype: object>

In [29]:
df["ph_2015"].replace("< LOD",1).min()

2.6

In [30]:
df[cat_col]

,lc1_2015,lu1_2015,oc_2018,caco3_2018,p_2018,n_2018,k_2018,lc1_2018,lu1_2018,lc1_2009,lu1_2009
0,321,21012,66.1,94.020382,15,4.6,99.8,321,21012,320,21012
1,322,21012,64,94.020382,13,2.6,44,322,21012,320,21036
2,420,21042,102.1,94.020382,29.9,8.1,238.7,420,21011,420,21011
3,520,21012,340.5,94.020382,51.3,28,128.5,520,21012,510,21012
4,420,21011,147.2,94.020382,17.8,9.3,240.2,420,21011,520,21011
...,...,...,...,...,...,...,...,...,...,...,...
13278,520,21011,36.2,94.020382,19.7,4.6,141.4,520,21011,520,21011
13279,520,21011,62,11,24,7.1,146.1,520,21011,520,21011
13280,520,21011,52.3,5,10,5.6,96.8,520,21011,520,21011
13281,520,21011,27.1,94.020382,< LOD,3.4,45.7,520,21011,520,21011
13282,310,21012,23.1,94.020382,13.9,2.1,185.8,310,21012,310,21012

In [31]:
num_col

['point_id',
 'ph_2015',
 'ec_2015',
 'oc_2015',
 'caco3_2015',
 'p_2015',
 'n_2015',
 'k_2015',
 'elevation_2015',
 'ph_2018',
 'ec_2018',
 'elevation_2018',
 'bd_0_10',
 'bd_10_20',
 'survey_erosion_signs',
 'ph_2009',
 'oc_2009',
 'caco3_2009',
 'p_2009',
 'n_2009',
 'k_2009',
 'elevation_2009']

In [32]:
for i in ["oc_2018","caco3_2018","p_2018","n_2018","k_2018"]:
    num_col.append(i)

In [33]:
no_df.nunique()

point_id                13283
ph_2015                    61
ec_2015                  2751
oc_2015                  1761
caco3_2015                666
p_2015                   1276
n_2015                    292
k_2015                   4428
elevation_2015           1051
lc1_2015                   62
lu1_2015                   19
ph_2018                    60
ec_2018                  3416
oc_2018                  1866
caco3_2018                665
p_2018                   1156
n_2018                    293
k_2018                   4578
elevation_2018           1310
lc1_2018                   64
lu1_2018                   24
bd_0_10                  1456
bd_10_20                 1365
survey_erosion_signs        1
ph_2009                   529
oc_2009                  1769
caco3_2009                667
p_2009                  12378
n_2009                    565
k_2009                   4575
elevation_2009           1040
lc1_2009                   59
lu1_2009                   22
dtype: int64

In [34]:
num_col

['point_id',
 'ph_2015',
 'ec_2015',
 'oc_2015',
 'caco3_2015',
 'p_2015',
 'n_2015',
 'k_2015',
 'elevation_2015',
 'ph_2018',
 'ec_2018',
 'elevation_2018',
 'bd_0_10',
 'bd_10_20',
 'survey_erosion_signs',
 'ph_2009',
 'oc_2009',
 'caco3_2009',
 'p_2009',
 'n_2009',
 'k_2009',
 'elevation_2009',
 'oc_2018',
 'caco3_2018',
 'p_2018',
 'n_2018',
 'k_2018']

In [35]:
for i in num_col:
    #no_df=df[i].dropna().apply(lambda x: convert_to_number(x))
    #no_df=no_df.replace("< LOD",1000)
    #no_df=no_df.replace("<  LOD",1000)
    #no_df=no_df.replace("<0.0",1000)
    df[i][(df[i] == "< LOD") | (df[i] == "<  LOD") | (df[i] == "<0.0")] = 0.01

    
    df[i]=df[i].apply(lambda x: convert_to_number(x))

C:\Users\vibu\AppData\Local\Temp\ipykernel_30172\2741629522.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[i][(df[i] == "< LOD") | (df[i] == "<  LOD") | (df[i] == "<0.0")] = 0.01

In [36]:
df["survey_erosion_signs"]=df["survey_erosion_signs"].replace(np.nan,0)

In [37]:
df["survey_erosion_signs"].value_counts()

0.0    12827
1.0      456
Name: survey_erosion_signs, dtype: int64

In [38]:
def satrification(df,column):
    value_list=df[column].value_counts().sort_values(ascending=False)
    df_0=df[df[column]==value_list.index[0]]
    df_1=df[df[column]==value_list.index[1]]
    df0_sampled = df_0.sample(n=len(df_1), random_state=2).copy()
    df_new=pd.concat([df_1,df0_sampled],axis=0)
    return df_new
df_ml=satrification(df,"survey_erosion_signs")

In [39]:
df_ml

,point_id,ph_2015,ec_2015,oc_2015,caco3_2015,p_2015,n_2015,k_2015,elevation_2015,lc1_2015,...,survey_erosion_signs,ph_2009,oc_2009,caco3_2009,p_2009,n_2009,k_2009,elevation_2009,lc1_2009,lu1_2009
42,34743334.0,4.8,67.70,28.4,0.0,26.2,3.6,73.2,220.0,520,...,1.0,5.47,37.7,0.0,518.86,3.9,397.0,169.0,520,21011
70,35263590.0,4.2,62.60,54.0,1.0,22.7,5.4,313.8,420.0,520,...,1.0,5.07,45.3,2.0,1018.65,3.7,149.3,374.0,520,21011
255,51582918.0,5.0,18.38,45.7,0.0,20.6,4.6,159.8,301.0,310,...,1.0,5.63,38.3,7.0,541.05,1.6,128.9,298.0,310,21040
267,52182946.0,4.4,6.54,22.7,0.0,6.1,2.3,100.4,298.0,310,...,1.0,4.44,13.2,1.0,220.82,1.3,80.4,322.0,330,21012
277,50822946.0,5.5,7.22,19.5,0.0,23.9,2.4,147.4,694.0,520,...,1.0,5.50,28.4,1.0,624.81,2.8,162.1,693.0,530,21011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10067,30181858.0,6.9,12.82,13.0,2.0,4.4,1.3,121.7,529.0,520,...,0.0,6.60,8.7,0.0,299.63,0.9,109.1,518.0,212,21011
11728,42483466.0,7.2,20.00,10.6,52.0,17.2,1.2,92.4,-4.0,530,...,0.0,7.19,16.5,47.0,450.33,1.3,85.0,10.0,530,21040
6071,37282610.0,5.8,24.30,16.9,0.0,60.8,2.1,263.4,439.0,211,...,0.0,5.02,12.4,0.0,548.20,1.3,154.6,410.0,530,21011
12484,46763004.0,6.3,16.06,20.0,0.0,40.5,2.2,278.8,255.0,216,...,0.0,6.65,17.1,2.0,732.04,1.7,263.3,254.0,216,21011
6124,37462568.0,4.7,44.70,56.7,0.0,30.7,4.4,171.4,700.0,520,...,0.0,4.62,57.0,0.0,976.19,3.6,79.2,686.0,520,21011

In [40]:
# Define Model Inputs (X) and Output (y)
X = df_ml.drop("survey_erosion_signs",axis=1)
y = df_ml["survey_erosion_signs"]

In [41]:

from sklearn.model_selection import cross_val_score, cross_validate

In [42]:
from sklearn.linear_model import LogisticRegression

In [43]:
# Split both Inputs (X) and Ouput (y) into training set (70%) and testing set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)
# Create the model "lg"
lg = LogisticRegression(solver='lbfgs', # optimization solver
                        max_iter=10000) # maximum iterations: set a big number to make sure the optimization solver will
# run enough iterations to let the model converge

# Fit the model to the training set
lg.fit(X_train,y_train)

LogisticRegression(max_iter=10000)

In [44]:
print(lg.score(X_train, y_train), '(Train Accuracy)')

0.6724137931034483 (Train Accuracy)

In [45]:
print(lg.score(X_test, y_test), '(Test Accuracy)')

0.635036496350365 (Test Accuracy)

In [48]:
lrc_gsv = LogisticRegression(random_state=42)

param_grid= {'penalty': ['l1', 'l2', 'elasticnet',None],
              'C': [0.1, 0.5, 1, 5, 10],
              'fit_intercept': [True, False],
              'solver': ['newton-cg', 'lbfgs', 'liblinear', 'sag'],
             
              'max_iter': [10, 50, 100, 500, 1000]}


gs_lrc = GridSearchCV(lrc_gsv, param_grid=param_grid, scoring='accuracy', cv= 10, n_jobs=-1)
# cv: number of partitions for cross validation


# n_jobs: number of jobs to run in parallel, -1 means using all processors

gs_lrc = gs_lrc.fit(X_train,y_train) # 

print(gs_lrc.best_score_)
print(gs_lrc.best_params_)

0.6927827380952382
{'C': 10, 'fit_intercept': False, 'max_iter': 10, 'penalty': 'l1', 'solver': 'liblinear'}

C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning:
5500 fits failed out of a total of 8000.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or 'none' penalties, got l1 penalty.

--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver newton-cg supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 71, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
500 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver sag supports only 'l2' or 'none' penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
2000 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\linear_model\_logistic.py", line 55, in _check_solver
    raise ValueError(
ValueError: Logistic Regression supports only penalties in ['l1', 'l2', 'elasticnet', 'none'], got None.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\model_selection\_search.py:953: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.68499504        nan 0.66800595 0.5140873
 0.50302579 0.49375           nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68968254        nan 0.68816964 0.51081349 0.68196925 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68968254        nan
 0.68187004 0.51081349 0.68196925 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68968254        nan 0.68028274 0.51081349
 0.68196925 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68968254        nan 0.68028274 0.51081349 0.68196925 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68497024        nan
 0.66488095 0.5140873  0.50302579 0.49375           nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.69124504        nan 0.68816964 0.51081349
 0.68196925 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69124504        nan 0.68187004 0.51081349 0.68196925 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.69124504        nan
 0.68028274 0.51081349 0.68196925 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.69124504        nan 0.68028274 0.51081349
 0.68196925 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68653274        nan 0.66959325 0.5140873  0.50302579 0.49375
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68655754        nan
 0.68973214 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68655754        nan 0.68184524 0.51081349
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68655754        nan 0.67867063 0.51081349 0.67884425 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68655754        nan
 0.67867063 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68650794        nan 0.66956845 0.5140873
 0.50302579 0.49375           nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68655754        nan 0.68973214 0.51081349 0.68040675 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68812004        nan
 0.68497024 0.51081349 0.68040675 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68812004        nan 0.68023313 0.51081349
 0.68040675 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68812004        nan 0.68023313 0.51081349 0.68040675 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.69122024        nan
 0.66800595 0.5140873  0.50302579 0.49375           nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68965774        nan 0.68658234 0.51081349
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68965774        nan 0.68340774 0.51081349 0.67884425 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68965774        nan
 0.68025794 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68965774        nan 0.68025794 0.51081349
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69122024        nan 0.66800595 0.5140873  0.50302579 0.49375
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68338294        nan
 0.68660714 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68338294        nan 0.67562004 0.51081349
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68338294        nan 0.68030754 0.51081349 0.67884425 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68338294        nan
 0.68030754 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68965774        nan 0.67115575 0.5140873
 0.50302579 0.49375           nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68807044        nan 0.68660714 0.51081349 0.67571925 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.69119544        nan
 0.67872024 0.51081349 0.67571925 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.69119544        nan 0.68179563 0.51081349
 0.67571925 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69119544        nan 0.68179563 0.51081349 0.67571925 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.69122024        nan
 0.66959325 0.5140873  0.50302579 0.49375           nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68960813        nan 0.68658234 0.51081349
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69273313        nan 0.68187004 0.51393849 0.67884425 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.69273313        nan
 0.68023313 0.51393849 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.69273313        nan 0.68023313 0.51393849
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68809524        nan 0.66800595 0.5140873  0.50302579 0.49375
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68650794        nan
 0.69129464 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68807044        nan 0.68345734 0.51081349
 0.67884425 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68807044        nan 0.68812004 0.51081349 0.67884425 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68807044        nan
 0.68812004 0.51081349 0.67884425 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.69278274        nan 0.66959325 0.5140873
 0.50302579 0.49375           nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.69117063        nan 0.68658234 0.51081349 0.68353175 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan 0.68960813        nan
 0.68340774 0.51081349 0.68353175 0.5140873         nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.68960813        nan 0.68182044 0.51081349
 0.68353175 0.5140873         nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.68960813        nan 0.68182044 0.51081349 0.68353175 0.5140873
        nan        nan        nan        nan        nan        nan
        nan        nan]
  warnings.warn(
C:\Users\vibu\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\svm\_base.py:1225: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

In [49]:
lrc_gsv.fit(X_train, y_train)
print(lrc_gsv.score(X_train, y_train), '(Train Accuracy)')
print(lrc_gsv.score(X_test, y_test), '(Test Accuracy)')

0.6724137931034483 (Train Accuracy)
0.635036496350365 (Test Accuracy)

In [ ]:
random_forest_baseline=RandomForestClassifier()
random_forest_baseline.fit(X_train, y_train)
print("train score",random_forest_baseline.score(X_train,y_train))
print("test score",random_forest_baseline.score(X_test,y_test))

In [47]:
from sklearn.model_selection import GridSearchCV

In [ ]:
RandomForest_gsv = RandomForestClassifier(random_state=42)
param_grid = {
    
              "criterion" : ["gini", "entropy"], 
              "n_estimators":[50,100,200],
              "min_samples_leaf" : [5, 10,15,20], 
              "min_samples_split" : [8, 16,32], 
              'max_depth' : [8,16,32],
              "bootstrap":["True","False"],
              "max_features":["sqrt","log2",None]
             }

R_gcv = GridSearchCV(RandomForest_gsv, param_grid=param_grid, scoring='accuracy', cv= 10, n_jobs=-1)
# cv: number of partitions for cross validation


# n_jobs: number of jobs to run in parallel, -1 means using all processors

gs = R_gcv.fit(X_train,y_train) # 

print(gs.best_score_)
print(gs.best_params_)

In [ ]:
RandomForest_gsv = RandomForestClassifier(random_state=42)
RandomForest_gsv.set_params(**gs.best_params_)
RandomForest_gsv.fit(X_train, y_train)
print("train score",RandomForest_gsv.score(X_train,y_train))
print("test score",RandomForest_gsv.score(X_test,y_test))

In [ ]:
from xgboost import XGBClassifier

In [ ]:
xgb=XGBClassifier(random_state=42)
param_grid = {
    
               "learning_rate":[0.0001,0.001],
               "n_estimators":[5,10,15]
             }

xgb_gcv = GridSearchCV(xgb, param_grid=param_grid, scoring='accuracy', cv= 10, n_jobs=-1)
# cv: number of partitions for cross validation


# # n_jobs: number of jobs to run in parallel, -1 means using all processors

xgb=xgb_gcv.fit(X_train, y_train)
print(xgb.best_score_)
print(xgb.best_params_)

In [ ]:
xgb_gcv.fit(X_train, y_train)
print("train score",xgb_gcv.score(X_train,y_train))
print("test score",xgb_gcv.score(X_test,y_test))