<h1>Load 2018 data </h1>

In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import numpy as np

In [11]:
df_2009_path = "..\df_2009.csv"
df_2015_path = "..\df_2015.csv"
df_2018_path = "..\df_2018_with_bd_erosion.csv"
metadata_path = "sra_metadata_5d8517e0-8bb8-4a34-ba02-26c397dea5a6.csv"

In [12]:
df_2009 = pd.read_csv(df_2009_path, delimiter=",")
df_2015 = pd.read_csv(df_2015_path, delimiter=",")
df_2018 = pd.read_csv(df_2018_path, delimiter=",")
df_metadata = pd.read_csv(metadata_path, delimiter=",")

In [13]:
df_soil = pd.merge(df_2015, df_2018, how='outer', on='point_id')
df_soil_total = pd.merge(df_soil, df_2009, how='outer', on='point_id')
df_soil_total

,point_id,ph_2015,ec_2015,oc_2015,caco3_2015,p_2015,n_2015,k_2015,elevation_2015,lc1_2015,...,survey_erosion_signs,ph_2009,oc_2009,caco3_2009,p_2009,n_2009,k_2009,elevation_2009,lc1_2009,lu1_2009
0,34103754,3.9,44.20,25.5,0.0,42.9,2.8,24.6,158.0,H11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,34443774,3.1,46.40,503.5,0.0,164.9,19.9,460.3,500.0,H12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,35163814,4.9,15.85,51.4,0.0,26.9,4.3,173.2,404.0,H11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,32323656,3.0,26.90,470.3,0.0,102.8,16.1,313.0,364.0,H12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,34463934,3.9,28.40,43.1,1.0,6.3,2.3,38.6,315.0,D20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27695,90000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.17,11.5,10.0,1170.0,1.3,882.4,45.0,B,MISSING
27696,90000002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.38,7.1,15.0,1297.0,1.1,967.2,48.0,B,MISSING
27697,90000003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.45,16.0,60.0,939.0,1.4,215.6,89.0,B,MISSING
27698,90000004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.54,16.3,91.0,545.0,1.4,276.4,55.0,B,MISSING
27699,90000005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,7.50,23.4,88.0,497.0,2.2,336.5,51.0,B,MISSING

In [100]:
df_soil_ml = df_soil_total.loc[df_soil_total['ph_2009'].notnull() & df_soil_total['ph_2015'].notnull() & df_soil_total['ph_2018'].notnull()]
df_soil_ml

,point_id,ph_2015,ec_2015,oc_2015,caco3_2015,p_2015,n_2015,k_2015,elevation_2015,lc1_2015,...,survey_erosion_signs,ph_2009,oc_2009,caco3_2009,p_2009,n_2009,k_2009,elevation_2009,lc1_2009,lu1_2009
4246,33883766,3.8,41.50,103.1,0.0,34.7,7.7,69.6,375.0,C21,...,NaN,3.92,285.3,0.0,1092.76,14.1,209.3,340.0,C20,U120
4248,35363916,3.2,4.21,17.9,0.0,20.8,0.8,7.9,68.0,C22,...,NaN,3.01,205.7,0.0,278.45,6.1,246.0,8.0,C20,U361
4259,33823392,3.9,43.00,96.3,0.0,31.6,7.8,93.5,243.0,D20,...,NaN,4.37,274.7,0.0,570.20,17.3,210.0,179.0,D20,U111
4266,33983652,4.0,58.80,368.3,0.0,41.3,24.3,94.1,276.0,E20,...,NaN,3.58,405.0,1.0,1264.19,22.8,98.1,222.0,E10,U120
4269,35383866,4.0,146.90,128.8,0.0,40.0,9.8,195.8,406.0,D20,...,NaN,4.60,288.7,0.0,780.83,14.8,530.6,346.0,E20,U111
4271,33503744,3.6,28.90,244.7,0.0,37.2,12.2,201.7,175.0,D20,...,NaN,3.67,133.7,0.0,461.11,10.1,261.6,110.0,E20,U111
4273,33903630,3.5,32.70,483.2,0.0,74.7,15.7,409.7,122.0,H12,...,NaN,3.15,445.8,1.0,572.40,14.8,446.4,71.0,E20,U111
4275,33863294,3.7,66.30,213.9,0.0,105.6,14.4,175.1,429.0,E20,...,NaN,3.90,326.8,3.0,1087.20,17.6,310.8,386.0,E20,U111
4276,36983250,3.4,25.70,164.1,0.0,78.5,9.2,245.5,93.0,C10,...,NaN,2.85,329.1,0.0,482.48,15.0,665.2,59.0,C10,U120
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21846,47402702,3.6,15.75,101.1,1.0,32.9,6.0,93.6,788.0,C21,...,NaN,3.61,153.9,0.0,401.44,7.0,101.4,797.0,C20,U120
21847,47522710,3.5,24.90,105.1,0.0,71.2,6.5,89.3,600.0,C21,...,NaN,3.75,108.4,2.0,895.88,5.7,92.6,615.0,C20,U120
21849,45242722,6.8,16.18,27.7,54.0,11.3,2.3,56.6,625.0,E20,...,NaN,4.34,230.4,1.0,897.20,13.4,109.2,629.0,E20,U111
21851,45562732,7.0,125.10,64.5,78.0,46.2,5.9,134.8,474.0,C31,...,NaN,6.95,107.3,166.0,310.48,7.8,318.8,466.0,C10,U120
21853,45542694,5.0,10.00,16.8,0.0,3.5,2.0,35.7,885.0,E20,...,NaN,5.75,36.6,2.0,1017.05,3.7,89.5,879.0,E20,U111
21854,45402772,6.9,81.00,49.9,8.0,49.3,5.6,200.1,477.0,E20,...,NaN,6.67,26.3,6.0,826.83,1.4,250.0,430.0,E20,U111
21856,45882618,6.8,65.10,53.9,3.0,16.6,5.9,90.0,630.0,E20,...,NaN,6.99,35.6,13.0,1202.65,3.5,58.6,619.0,E20,U111
21857,45342706,6.0,30.70,24.2,0.0,4.6,3.2,32.7,719.0,E20,...,NaN,5.66,24.5,1.0,940.35,2.9,41.1,710.0,E20,U111
21858,47742660,4.2,7.30,26.0,0.0,9.6,2.2,162.0,344.0,C10,...,NaN,4.18,25.5,0.0,911.54,1.9,146.5,342.0,C10,U120

In [102]:
df_soil_ml.to_csv("merged_soil_intersects.csv", index=False)

In [84]:
df_soil_ml.isna().sum()

point_id                0
ph_2015                 0
ec_2015                 0
oc_2015                 0
caco3_2015              0
p_2015                  0
n_2015                  0
k_2015                  0
elevation_2015          0
lc1_2015                0
lu1_2015                0
ph_2018                 0
                       ..
bd_0_10                 0
bd_10_20                0
survey_erosion_signs    0
ph_2009                 0
oc_2009                 0
caco3_2009              0
p_2009                  0
n_2009                  0
k_2009                  0
elevation_2009          0
lc1_2009                0
lu1_2009                0
Length: 33, dtype: int64

In [121]:
df_soil_ml.loc[:, 'survey_erosion_signs'] = df_soil_ml['survey_erosion_signs'].fillna(0)

mean_bd_10 = df_soil_ml['bd_0_10'].mean()
mean_bd_20 = df_soil_ml['bd_10_20'].mean()

df_soil_ml.loc[:, ['bd_0_10']] = df_soil_ml['bd_0_10'].fillna(mean_bd_10)
df_soil_ml.loc[:, ['bd_10_20']] = df_soil_ml['bd_10_20'].fillna(mean_bd_20)

C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\1315304456.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml.loc[:, 'survey_erosion_signs'] = df_soil_ml['survey_erosion_signs'].fillna(0)
C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\1315304456.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml.loc[:, ['bd_0_10']] = df_soil_ml['bd_0_10'].fillna(mean_bd_10)
C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\1315304456.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml.loc[:, ['bd_10_20']] = df_soil_ml['bd_10_20'].fillna(mean_bd_20)

In [142]:
# LODs
df_soil_ml['caco3_2018'].replace("<  LOD", 0.1, inplace=True)
mean_caco3 = df_soil_ml['caco3_2018'].notnull().mean()
df_soil_ml['caco3_2018'].fillna(mean_caco3, inplace=True)

mean_ec = df_soil_ml['ec_2018'].mean()
df_soil_ml['ec_2018'].fillna(mean_ec, inplace=True)

df_soil_ml['p_2018'].replace("< LOD", 0, inplace=True)
mean_p = df_soil_ml['p_2018'].notnull().mean()
df_soil_ml['p_2018'].fillna(mean_p, inplace=True)

C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\2700484274.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml['caco3_2018'].replace("<  LOD", 0.1, inplace=True)
C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\2700484274.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml['caco3_2018'].fillna(mean_caco3, inplace=True)
C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\2700484274.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml['ec_2018'].fillna(mean_ec, inplace=True)
C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\2700484274.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml['p_2018'].replace("< LOD", 0, inplace=True)
C:\Users\jgcc1\AppData\Local\Temp\ipykernel_43048\2700484274.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_soil_ml['p_2018'].fillna(mean_p, inplace=True)

In [147]:
df_soil_ml.to_csv("merged_soil_intersects_nonan.csv", index=False)